### ISSUE TITLE
Running commitLock twice creates empty commits

### ISSUE THREAD

**Issue by itissid** [nebula-plugins/gradle-dependency-lock-plugin#102]
The commit lock feature creates empty commits if there is no lock file to commit. This is possibly a bug. Version 3.0.1 Gradle  2.12

**Comment by rspieldenner** [comment]
i believe this is fixed in the newer versions. Will verify and close if that is the case.

**Comment by praveengs** [comment]
Hi any update on this one? I am using dependency-lock version 4.3.0 and gradle-git-scm version 3.0.1 and gradle 3.1.

I still get empty push events when I do a commitLock. Even though the push doesnt show any changed files.

Any help would be appreciated.

Thanks

**Comment by jonatan-ivanov** [comment]
@itissid @praveengs 

I had the same issue with gradle 4.0.2 and
```
id 'nebula.dependency-lock' version '4.9.4'
id 'nebula.gradle-git-scm' version '3.0.1'
```



I wanted to run `./gradlew clean generateLock saveLock build commitLock` nightly from my CI pipeline (jenkins).
Since I had the same "empty commit" issue, I hacked the `commitLock` task and inserted an action in the front of its action list which will stop the execution of the task if there is nothing to commit.

```groovy
commitLock {
    doFirst {
        if (org.ajoberstar.grgit.Grgit.open(rootProject.projectDir).status().unstaged.modified.isEmpty()) {
            throw new StopExecutionException('There is nothing to commit, stop.')
        }
    }
}
```

**Comment by rpalcolea** [comment]
This shouldn't be an issue with modern versions of the plugin and gradle

**Comment by jonatan-ivanov** [comment]
@rpalcolea Could you please post the PR which fixed this for the record?
